services:
  sonarqube:
    build:
      context: ../jenkins/images
      dockerfile: ../jenkins/images/Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes:/var/jenkins_home  # Persistencia de datos
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem
    driver: bridge
