services:
  rabbitmq-dev:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - ../cd/.env.dev
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bacsystem
    volumes:
      - ./volumes/dev:/var/lib/rabbitmq

  rabbitmq-test:
    container_name: rabbitmq-test
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - ../cd/.env.test
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      - bacsystem
    volumes:
      - ./volumes/test:/var/lib/rabbitmq
  rabbitmq-uat:
    container_name: rabbitmq-uat
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - ../cd/.env.uat
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "15674:15672"
      - "5674:5672"
    networks:
      - bacsystem
    volumes:
      - ./volumes/uat:/var/lib/rabbitmq
  rabbitmq-prod:
    container_name: rabbitmq-prod
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - ../cd/.env
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "15675:15672"
      - "5675:5672"
    networks:
      - bacsystem
    volumes:
      - ./volumes/prod:/var/lib/rabbitmq

networks:
  bacsystem:
    name: bacsystem
    driver: bridge