export enum ResponseCode {
    PROCESS_OK = '000',
    NOT_FOUND_DOCUMENT_ID = '001',
    NOT_FOUND_DOCUMENT_UUID = '002',
    INVALID_REQUEST_DOCUMENT_ID = '003',
    INVALID_REQUEST_DOCUMENT_UUID = '004',
    REQUEST_DOCUMENT_EXIST = '005',
    INTERNAL_SERVER_ERROR = '999',
}