CREATE TABLE IF NOT EXISTS BD_202115187.TB_PERFIL
(
    PERFIL_ID NUMERIC PRIMARY KEY NOT NULL,
    PERFIL    VARCHAR(45)

);

CREATE TABLE IF NOT EXISTS BD_202115187.TB_ESTUDIANTE
(
    DNI              CHAR(8) PRIMARY KEY NOT NULL,
    PERFIL_ID        NUMERIC             NOT NULL,
    COD_ALUMNO       VARCHAR(6),
    NOMBRES          VARCHAR(45),
    APELLIDOS        VARCHAR(45),
    FECHA_NACIMIENTO DATE,
    CONSTRAINT TB_ESTUDIANTE_FK1 FOREIGN KEY (PERFIL_ID) REFERENCES TB_PERFIL (PERFIL_ID)
);

CREATE TABLE IF NOT EXISTS BD_202115187.CREDENCIALES
(
    ESTUDIANTE_DNI CHAR(8) NOT NULL,
    CORREO         VARCHAR(45),
    PASSWORD       VARCHAR(45),
    ESTADO         CHAR(1),
    CONSTRAINT CREDENCIALES_FK FOREIGN KEY (ESTUDIANTE_DNI) REFERENCES TB_ESTUDIANTE (DNI)
);

CREATE TABLE IF NOT EXISTS BD_202115187.CURSO
(
    CURSO_ID     NUMERIC PRIMARY KEY NOT NULL,
    COD_CURSO    CHAR(4),
    NOMBRE_CURSO VARCHAR(45),
    CICLO        VARCHAR(45),
    ESTADO       CHAR(1)
);

CREATE TABLE IF NOT EXISTS BD_202115187.ESTUDIANTE_CURSO
(
    TB_ESTUDIANTE_DNI CHAR(8) NOT NULL,
    CURSO_CURSO_ID    NUMERIC NOT NULL,
    CONSTRAINT CREDENCIALES_FK1 FOREIGN KEY (TB_ESTUDIANTE_DNI) REFERENCES TB_ESTUDIANTE (DNI),
    CONSTRAINT CREDENCIALES_FK2 FOREIGN KEY (CURSO_CURSO_ID) REFERENCES CURSO (CURSO_ID)
);