services:
  server-ssh:
    build:
      context: ssh
      dockerfile: Dockerfile
    container_name: server-ssh
    restart: always
    hostname: server-ssh
    ports:
      - "2222:22"
    stdin_open: true
    tty: true
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem-net
    driver: bridge

