#/app /urs /lib
###### DOCKERFILE #######
FROM debezium/connect:latest AS base

LABEL autor="christian bacilio"
LABEL description="create image debezium version debezium/connect:latest"
LABEL version="1.0.0"


FROM base AS dev

EXPOSE 8083