services:
  pg-dcd014f7:
    build:
      context: ./pg
      dockerfile: Dockerfile
      #labels: dev
      target: dev
    container_name: pg-dcd014f7
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/dcd014f7:/var/lib/postgresql/data
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem-net-db
    driver: bridge