CREATE TABLE IF NOT EXISTS public.BS_APPLICATION (
    AP_ID NUMERIC(38, 0) NOT NULL,
    AP_UUID VARCHAR(36) NOT NULL,
    AP_DESCRIPTION VARCHAR(50),
    CONSTRAINT BS_APPLICATION_PK PRIMARY KEY (AP_ID),
    CONSTRAINT BS_APPLICATION_UN UNIQUE (AP_UUID)
);

