services:
  postgres-dev:
    build:
      context: images
      dockerfile: images/Dockerfile
      target: dev
    container_name: postgres-dev
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/dev:/var/lib/postgresql/data
    networks:
      - bacsystem
  postgres-test:
    build:
      context: images
      dockerfile: images/Dockerfile
      target: test
    container_name: postgres-test
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./volumes/test:/var/lib/postgresql/data
    networks:
      - bacsystem
  postgres-uat:
    build:
      context: images
      dockerfile: images/Dockerfile
      target: uat
    container_name: postgres-uat
    env_file:
      - .env.dev
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./volumes/uat:/var/lib/postgresql/data
    networks:
      - bacsystem

  postgres-prod:
    build:
      context: images
      dockerfile: images/Dockerfile
      target: uat
    container_name: postgres-prod
    env_file:
      - .env.dev
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - ./volumes/prod:/var/lib/postgresql/data
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem
    driver: bridge