services:
  jenkins:
    build:
      context: jenkins/images
      dockerfile: Dockerfile
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home  # Persistencia de datos
    networks:
      - bacsystem-infra

networks:
  bacsystem-infra:
    name: bacsystem-net-infra
    driver: bridge
