services:
  pg-db:
    build:
      context: pg
      dockerfile: Dockerfile
      target: dev
    container_name: pg-bd-app
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/16.3.20:/var/lib/postgresql/data
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem-net-db
    driver: bridge