services:
  pg-db:
    build:
      context: pg
      dockerfile: Dockerfile
      target: dev
    container_name: pg-bd-app
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/pg/17.3.20:/var/lib/postgresql/data
    networks:
      - bacsystem
  mysql-db:
    build:
      context: mysql
      dockerfile: Dockerfile
      target: dev
    container_name: mysql-bd-app
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./volumes/mysql/8.0.39:/var/lib/mysql
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem-net-db
    driver: bridge