services:
  jenkins:
    build:
      context: ./images
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../volumes/jenkins:/var/jenkins_home  # Persistencia de datos
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem
    driver: bridge
