microservice-postgres:
  build:
    context:
    dockerfile: Dockerfile
  container_name: microservice-postgres
  image: ${POSTGRES_IMAGE}
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
  restart: always
  volumes:
    - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  networks:
    - services-database
    - cinfe