apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  automountServiceAccountToken: false
  containers:
    - name: nginx
      image: nginx:1.14.2
      resources:
        limits:
          memory: 10Mi
          cpu: 1
      ports:
        - containerPort: 80
